/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HandoutRouteImport } from './routes/handout'
import { Route as IndexRouteImport } from './routes/index'

const HandoutRoute = HandoutRouteImport.update({
  id: '/handout',
  path: '/handout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/handout': typeof HandoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/handout': typeof HandoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/handout': typeof HandoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/handout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/handout'
  id: '__root__' | '/' | '/handout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandoutRoute: typeof HandoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/handout': {
      id: '/handout'
      path: '/handout'
      fullPath: '/handout'
      preLoaderRoute: typeof HandoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandoutRoute: HandoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
